export const types = {

    authCheckingStart: '[auth] Start checking login state',
    authCheckingFinish: '[auth] Finish checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authStartTokenRenew: '[auth] Start token renew',
    authLogout: '[auth] Logout',

    uiSetError: '[UI] Set Error',
    uiSetCorrect: '[UI] Set Correct',
    uiRemoveError: '[UI] Remove Error',
    uiStartLoading: '[UI] Start loading',
    uiFinishLoading: '[UI] Finish loading',
    uiStartLoadingCards: '[UI] Start loading cards',
    uiFinishLoadingCards: '[UI] Finish loading cards',
    uiSetActiveScreen: '[UI] Set active Screen',
    uiOpenDropMenu: '[UI] Open drop menu',
    uiCloseDropMenu: '[UI] Close drop menu',
    uiStartLoadingStudents: '[UI] Start loading students',
    uiFinishLoadingStudents: '[UI] Finish loading students',

    paySetActive: '[pay] Set Active',
    paySetCards: '[pay] Set Cards',
    paySetPrice: '[pay] Set Price',
    payClearActive: '[pay] Clear Active',
    payConceptPay: '[pay] Concept pay',
    payMethodPay: '[pay] Method pay',
    payThingToPay: '[pay] Material to pay',
    payClearModalData: "[pay] Clear modal data",
    payAmountToPay: "[pay] Set amount paying",
    paySetActiveAccount: "[pay] Set Active Acount",
    paySetFertilizers: "[pay] Set fertilizers",
    paySetIdPayment: "[pay] Set id payment",
    paySetPayments: '[pay] Set payments',
    paySetStudents: '[pay] set students',

    requestSetActive: '[request] Set Active',
    requestSetStudent: '[request] Set request Student',
    requestSetHistory: '[request] Set History Requests',
    requestDelete: '[request] Delete Request',
    requestClearActive: '[request] Clear Active',
    requestClearData: '[request] Clear request data',

}